### ISSUE TITLE
Prevent a React dev warning when a loading Query component is unmounted

### ISSUE THREAD

**Issue by jaydenseric** [jaydenseric/graphql-react#10]
If you unmount a `Query` component (specifically the `GraphQLQuery` component within it) while it is still loading a query, you see a React dev warning like this:

<img width="452" alt="screen shot 2018-09-26 at 3 23 12 pm" src="https://user-images.githubusercontent.com/1754873/46059308-fa6ad180-c1a1-11e8-8ce9-3d2fe8e2e691.png">

This is because a `setState` call happens after the request is complete to update the loading state as `false`, see [here](https://github.com/jaydenseric/graphql-react/blob/v2.0.0/src/components.mjs#L188). This should be prevented from happening after the component has unmounted.

**Comment by xjamundx** [comment]
I'm doing a thing where I use the `Redirect` component from `@reach/router` and see this a lot.

**Comment by jaydenseric** [comment]
Yep, it's annoying but at least harmless. I hope to be able to get to it this weekend; I've recently been busy soft-launching https://enamor.app (which BTW happens to use `graphql-react` ✌️).

**Comment by jaydenseric** [comment]
🚢 [Fixed in v3](https://github.com/jaydenseric/graphql-react/releases/tag/v3.0.0)
