### ISSUE TITLE
Does this work out of the box with ApolloServer?

### ISSUE THREAD

**Issue by joelgetaction** [jaydenseric/graphql-react#13]
Hey, this looks great, thanks so much for making this available!  I like how light and clear the API is and I like that it doesn't use TS.  :-)

I'm currently using ApolloClient and ApolloServer (via apollo-server-express).  ApolloServer seems to work really well but ApolloClient seems to have some serious bugs around caching ...

***My Question:*** If I swap this out for ApolloClient, should `graphql-react` just work directly with ApolloServer without any server changes needed?

I ask because Relay seems to need a "RelayServer" so I'm avoiding that.  I'd like to use `graphql-react` talking to `ApolloServer` and I'm not sure if that would work directly?

Sorry for filing this as an issue, I just wasn't sure how to ask this question otherwise (if there's a better way, please let me know) ...

Thanks again for all of your hard work on this!  :-)

P.S. I will need to use this in ReactNative as well - do you see any reason why it wouldn't also work in RN?  Thanks.

**Comment by jaydenseric** [comment]
> If I swap this out for ApolloClient, should graphql-react just work directly with ApolloServer without any server changes needed?

Yes! It should work with any GraphQL server.

As for React Native, I'm not sure; probably. The file uploads part (via the [extract-files](https://npm.im/extract-files) dependency) supports it.
