### ISSUE TITLE
Cancel in-flight requests when they are invalidated

### ISSUE THREAD

**Issue by mike-marcacci** [jaydenseric/graphql-react#24]
When an in-progress query is invalidated (due to variables changing, or the react component being removed from the virtual DOM, etc) we need to cancel the request and open up space in the browser's request queue.

For me, this is especially important in a "search-while-typing" interface, where in-flight queries are frequently invalidated by more user input.

**Comment by jaydenseric** [comment]
Pretty excited about how easy this is going to be soon with the new API…

<img width="1078" alt="Screen Shot 2021-03-19 at 3 54 19 pm" src="https://user-images.githubusercontent.com/1754873/111733220-82da1100-88cb-11eb-8907-179508ed2646.png">
