### ISSUE TITLE
Suspense mode ?

### ISSUE THREAD

**Issue by revskill10** [jaydenseric/graphql-react#29]
It would be useful if we could enable `suspense:true` option , so that the library is compatible with future SSR Suspense release.

**Comment by jaydenseric** [comment]
My preference is to wait for the stable release of the official React Suspense APIs. Depending on what the final APIs looks like, we might be able to get rid of the `ssr()` function and redo the way loading and perhaps even cache works.

We can cross that bridge when the time comes.
