### ISSUE TITLE
hello can you convert for native js?

### ISSUE THREAD

**Issue by timeshift92** [jaydenseric/graphql-react#40]

**Comment by jaydenseric** [comment]
I'm not quite sure what you mean, exactly?

**Comment by timeshift92** [comment]
I write my projects on svelte and would like to use your library but it is written only for react, is there any way to rewrite it under native js? If so, can you tell? I am ready to do it.

**Comment by jaydenseric** [comment]
The [`GraphQL`](https://github.com/jaydenseric/graphql-react#class-graphql) class is a non-React specific GraphQL client, that could be useful for you :)

**Comment by timeshift92** [comment]
cool thx =)

**Comment by timeshift92** [comment]
Do you have any ideas on subscription?

**Comment by jaydenseric** [comment]
@timeshift92 GitHub issues are more for bugs than general conversation, but if you would like to keep up with subscriptions support you can subscribe to https://github.com/jaydenseric/graphql-react/issues/15. 

Hypothetically a dedicated subscriptions client and React hook could be created, that would compliment the existing `graphql-react` API.

After a fair bit of dabbling, there are two main reasons I haven't shipped subscriptions support:

1. I don't have a need for them, and there are a lot of engineering complexities that can be avoided just by polling.
2. There is no standard GraphQL subscriptions WebSocket protocol. Apollo has made quite a few changes to their protocol, and it's not well documented.
