### ISSUE TITLE
Possibly missing files within package

### ISSUE THREAD

**Issue by ivanji** [jaydenseric/graphql-react#45]
If we look at the official NextJS example, under examples/with-graphql-react/next.config.js- the following package is required:  ```const { withGraphQLConfig } = require('next-graphql-react/server')```

When installing next-graphql-react now the 'server' path is missing. If things have changed in the latest versions please update example.

Thanks

**Comment by jaydenseric** [comment]
See https://github.com/vercel/next.js/issues/11014#issuecomment-640161780 .

**Comment by ivanji** [comment]
Thanks.
