### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by sirganya** [jaydenseric/graphql-react#54]
Without a license anyone who uses this library is infringing your copyright. Do you plan to open source the code? Have I missed the licensing blurb? Without it you might find adoption is limited. Thanks.

**Comment by jaydenseric** [comment]
Please see https://github.com/jaydenseric/apollo-upload-client/issues/233#issuecomment-718209156 .

**Comment by sirganya** [comment]
My bad.

**Comment by jaydenseric** [comment]
I've decided to add licence files to my projects moving forward. My primary concern with doing so in the past was that it bloats the package install size within `node_modules`, but I'm pivoting to [Deno](https://deno.land) which doesn't have this problem as only modules imported in your code get cached to your local disk. Node.js users don't seem too fussed about installing the licence files, it's the norm. Adding a license file helps out some people get approvals in organisations with heavy process, and while my package could be clearly seen to be MIT License with me as the author via the `package.json` fields, GitHub's displaying of repo licence info with nice UI is only based on the presence of a license file.
