### ISSUE TITLE
error - unhandledRejection: TypeError: Head.rewind is not a function -> can't get the official example to work

### ISSUE THREAD

**Issue by philohelp** [jaydenseric/graphql-react#58]
Hello,
I'm trying to yarn create next-app --example with-graphql-react with-graphql-react-app but with no success. I try yarn dev and then get Head.rewind was removed in next v11.
Is the project compatible with next's last version ?
Thanks in advance

**Comment by philohelp** [comment]
closing as it seems I'm on the wrong repo - this has to see with next-graphql-react, sorry.

**Comment by jaydenseric** [comment]
Sorry to hear it's been a bit of a confusing experience for you. I updated the Next.js example via [a PR](https://github.com/vercel/next.js/pull/26435) in June, but the Next.js team still haven't reviewed and merged it all these months later :(

You should have a better time if you work off the updated example in the PR:

https://github.com/vercel/next.js/pull/26435

**Comment by philohelp** [comment]
Fantastic, many thanks
