### ISSUE TITLE
Type 'Dispatch<any>' is not assignable to type '() => void'

### ISSUE THREAD

**Issue by bandinopla** [jaydenseric/graphql-react#62]
The jsdoc says this function returns:
https://github.com/jaydenseric/graphql-react/blob/38a7abcebf7e6d0e4e821c5c3982e8c1cbfae67e/useForceUpdate.mjs#L7

but then here:
https://github.com/jaydenseric/graphql-react/blob/38a7abcebf7e6d0e4e821c5c3982e8c1cbfae67e/useForceUpdate.mjs#L12

It grabs the `dispatch` from `React.useReducer` which expects an action...
https://es.react.dev/reference/react/useReducer#dispatch

This makes typescript cry: 
```Target signature provides too few arguments. Expected 1 or more, but got 0.```

I have set `skipLibCheck` to true but still get this error. I'm using vite... any ideas?

https://github.com/jaydenseric/graphql-react/pull/63

**Comment by jaydenseric** [comment]
I've done a type check on the `useForceUpdate.mjs` module with the latest version of TypeScript and `@types` packages installed, and can't see any errors. Can you please share what version of each of these you have installed:

- `@types/react`
- `react`
- `typescript`

Also, can you please check if something in your project TS config is different to here, and share what changes to it reproduce the error?

https://github.com/jaydenseric/graphql-react/blob/38a7abcebf7e6d0e4e821c5c3982e8c1cbfae67e/jsconfig.json#L1-L11

**Comment by jaydenseric** [comment]
Note that the hook returns the type `React.DispatchWithoutAction`, which is a legit thing to do and that type comes from `@types/react`:

<img width="566" alt="Screenshot 2024-09-27 at 10 29 40 am" src="https://github.com/user-attachments/assets/b477a26a-ab93-4481-a2b8-080da29c7afc">

<img width="772" alt="Screenshot 2024-09-27 at 10 30 26 am" src="https://github.com/user-attachments/assets/95da49aa-f444-473f-9166-96f86c7354fa">

**Comment by jaydenseric** [comment]
Closing in the absence of a reply. If more information comes to light revealing there is an issue, we can reopen.
