### ISSUE TITLE
Passing URL parameters

### ISSUE THREAD

**Issue by murunwas** [jaydenseric/graphql-react#8]
Unable to get `nextjs` url parameters (query) on server-side using `getInitialProps`  using the `Provider`

 **WITH PROVIDER**
![image](https://user-images.githubusercontent.com/8838943/42831275-33e9425c-89ee-11e8-9b04-d0aebcdafe84.png)

**WITHOUT PROVIDER**
![image](https://user-images.githubusercontent.com/8838943/42831193-f56fd1ee-89ed-11e8-8341-94f19be12627.png)

**Comment by murunwas** [comment]
Thank you for the response, I just tweak the provider as shown on image below:

![image](https://user-images.githubusercontent.com/8838943/42884813-95ae1a10-8a9f-11e8-9224-e3969587fc16.png)
it's working fine but I'll try the advanced one, cheerz

**Comment by jaydenseric** [comment]
The issue seems resolved 🤞

**Comment by jaydenseric** [comment]
@murunwas you might be interested in the new way to to it with Next.js v7 and _app.js… https://github.com/jaydenseric/graphql-react-examples/blob/master/pages/_app.js#L3
